name: Build and Push to Docker Registry

on:
  push:
    branches:
      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [app, db-migrate]
        include:
          - target: app
            file: Dockerfile
            image: teable
          - target: db-migrate
            file: Dockerfile.db-migrate
            image: teable-db-migrate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_KEY }}

      - name: Login to Ali container registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}

      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          context: .
          file: dockers/teable/${{ matrix.file }}
          images: |
            registry.cn-shenzhen.aliyuncs.com/teable/${{ matrix.image }}
            ghcr.io/teableio/${{ matrix.image }}
          push: true
          cache-from: type=registry,ref=ghcr.io/teableio/${{ matrix.image }}:buildcache
          cache-to: type=registry,ref=ghcr.io/teableio/${{ matrix.image }}:buildcache,mode=max
